config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "home#index"

  resources :users do
    resources :posts do
      resources :likes, only: %i[create destroy]
      resources :comments, only: %i[create destroy]
    end
  end

  devise_scope :user do
    get "/login", to: "devise/sessions#new"
    get "/signup", to: "devise/registrations#new"
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index show] do
        resources :posts, only: %i[index create show update destroy] do
          resources :comments, only: %i[index create show update destroy]
          resources :likes, only: %i[create destroy]
        end
      end
    end
  end
end

app/views/shared/_comment.html.erb
<section class="comment">
  <p><%= comment.author.name %>: </p>
  <p><%= comment.text %></p>
  <div class="comment-interactions">
    <% if can? :destroy, comment %>
      <%= link_to "Delete", user_post_comment_path(user_id: comment.post.author.id, post_id: comment.post.id, id: comment.id), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
</section>

app/views/shared/_footer.html.erb
<footer>
  <p>Created by: <%= link_to "Yuvenal", "https://github.com/yuvenalmash" %></p>
</footer>

app/views/shared/_navbar.html.erb
<nav>
  <%= link_to "Inkwell Blog", root_path, id: "logo" %>
  <ul class="nav-links">
    <% if user_signed_in? %>
      <li><%= link_to "Users", users_path, class: current_page?(users_path) ? "active" : "" %></li>
      <li><%= link_to "Posts", user_posts_path(current_user), class: current_page?(user_posts_path(current_user)) ? "active" : "" %></li>
      <li><%= link_to "New Post", new_user_post_path(current_user), class: current_page?(new_user_post_path(current_user)) ? "active" : "" %></li>
      <li><%= link_to "My Profile", user_path(current_user), class: current_page?(user_path(current_user)) ? "active" : "" %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign In", '/login' %></li>
      <li><%= link_to "Sign Up", '/signup' %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_post.html.erb
<section class="post">
  <h3><%= link_to post.title, user_post_path(@user, post) %><h3>
  <p><%= post.text %></p>
  <div>
    <div class="post-interactions">
      <% if post.liked_by?(current_user) %>
        <%= link_to "Unlike", user_post_like_path(@user, post, post.likes.find_by(user_id: current_user.id)), method: :delete, class: "like-link", id: "like-link-#{post.id}", data: { post_id: post.id } %>
      <% else %>
        <%= link_to "Like", user_post_likes_path(@user, post), method: :post, class: "like-link", id: "like-link-#{post.id}", data: { post_id: post.id } %>
      <% end %>
      <%= link_to "Comment", user_post_comments_path(@user, post), class: "comment-link", data: { post_id: post.id } %>
      <% if can? :destroy, post %>
        <%= link_to "Delete", user_post_path(@user, post), method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
    <div class="post-counters">
      <p>Comments: <%= post.comments_counter %></p>
      <p>Likes: <span id="likes-counter-<%= post.id %>"><%= post.likes_counter %></span></p>
    </div>
  </div>
</section>
<div class="comment-form" id="comment-form-<%= post.id %>" style="display: none;">
  <%= form_with model: [ @user, post, Comment.new ], remote: true do |f| %>
    <%= f.text_field :text %>
    <%= f.submit "Comment" %>
  <% end %>
</div>

app/views/shared/_user.html.erb
<section class=user>
  <%= image_tag url_for(user.photo), class: 'user-image' %>
  <div class="user-info">
    <%= link_to user.name, user_path(user), class: 'user-name' %>
    <p class="user-counters">Number of posts: <%= user.posts_counter %></p>
  </div>
</section>